// Frontend/src/routes/DeviceEdit.vue
<template>
    <div v-if="device">
        <device-details v-bind:device="device" v-bind:disableType=true></device-details>
        <div>
            <label for="person">Person holding device:</label>
        </div>
        <div>
            <!--<input type="text" name="person" id="person" v-model="device.personDevice.person" />-->
            <v-select name="person" id="person" :options="personUsers" label="name">
            </v-select>
        </div>
    </div>
    <div v-else>
        Can't find device details.
    </div>
</template>

<script lang="ts">
    import Vue from 'vue';

    import { deviceView, personAllForUser } from '../api/device-api';
    
    export default Vue.extend({
        name: 'device-edit',
        props: ['deviceId'],
        data() {
            return {
                device: null,
                personUsers: null,
            };
        },
        created() {
            this.fetchDeviceDetails();
            this.fetchAllPersonForUser();
        },
        watch: {
            // call again the method if the route changes
            '$route': 'fetchDevice'
        },
        methods: {
            fetchDeviceDetails(): void {
                this.device = null;
                deviceView(this.deviceId).then(data => {
                    this.device = data;
                }).catch(e => {
                    alert('error:' + e); // Add error handling later
                });
            },
            fetchAllPersonForUser(): void {
                this.personUsers = null;
                personAllForUser().then(data => {
                    this.personUsers = data;
                }).catch(e => {
                    alert('error:' + e); // Add error handling later
                });
            }
        },
    });
</script>

// KeyBook/Svelte/src/components/DeviceEdit.svelte
﻿<svelte:options tag="device-edit-svelte" />
<script lang="ts">
    export let devicepersonlistjson;

    let devicepersonlist = JSON.parse(devicepersonlistjson);
    import DeviceDetails from './DeviceDetails.svelte';
    
    let personNames = {}
    import { GetPersonNamesAPI } from '../api/person';
    let getPersonNamesAPI = new GetPersonNamesAPI();
    getPersonNamesAPI.successCallback = r => { personNames = r.data; };
    getPersonNamesAPI.failedCallback = e => { alert('error: ' + e); /* Add error handling later */ }
    getPersonNamesAPI.call();

    let personId;
    if (devicepersonlist.device.personDevice != null) personId = devicepersonlist.device.personDevice.personId;
</script>
<main>
    <button on:click="{() => window.history.back()}">Back</button>
    <DeviceDetails
      bind:name={devicepersonlist.device.name}
      bind:identifier={devicepersonlist.device.identifier}
      bind:status={devicepersonlist.device.status}
      bind:type={devicepersonlist.device.type}
      disabletype=true />
    <div>
        <label for="person">Person holding device:</label>
    </div>
    <div>
        <select name="person" id="person" bind:value={personId}>
            <option value="">Not Used</option>
            {#each Object.keys(personNames) as personId}
                <option value="{personId}">{personNames[personId]}</option>
            {/each}
        </select>
    </div>
    <div>
        <form action="/Device/Save" method="POST">
            <input type="hidden" name="deviceid" id="deviceid" value={devicepersonlist.device.id} />
            <input type="hidden" name="name" id="name" value={devicepersonlist.device.name} />
            <input type="hidden" name="identifier" id="identifier" value={devicepersonlist.device.identifier} />
            <input type="hidden" name="status" id="status" value={devicepersonlist.device.status} />
            <input type="hidden" name="type" id="type" value={devicepersonlist.device.type} />
            <input type="hidden" name="personid" id="personid" value={personId} />
            <input type="hidden" name="frompersondetailspersonid" id="frompersondetailspersonid" value={devicepersonlist.fromPersonDetailsPersonId} />
            <button>Save device</button>
        </form>
    </div>
    <div>
        <label for="deviceActivityHistoryList">Device activity history:</label>
    </div>
    <table>
        {#each devicepersonlist.deviceActivityHistoryList as deviceActivityHistory}
	        <tr>
                <td>{deviceActivityHistory.recordDateTime}</td>
                <td>|</td>
                <td>{deviceActivityHistory.description}</td>
            </tr>
        {/each}
    </table>
</main>
