// Frontend/src/components/PersonDetails.vue
<template>
    <div>
        <div>
            <label for="name">Person Name:</label>
        </div>
        <div>
            <input type="text" name="name" id="name" v-model="person.name" />
        </div>
        <div v-if="!hideIsGone">
            <div>
                <label for="isgone">Person Is Gone:</label>
            </div>
            <div>
                <input type="checkbox" name="isgone" id="name" v-model="person.isGone" />
            </div>
        </div>
        <div>
            <label for="type">Person Type:</label>
        </div>
        <div>
            <input type="text" name="type" id="type" v-model="person.type" :disabled="disableType" />
        </div>
    </div>
</template>

<script lang="ts">
    import Vue from 'vue';

    export default Vue.extend({
        props: {
            'person': Object,
            'hideIsGone': {
                type: Boolean,
                default: false,
            },
            'disableType': {
                type: Boolean,
                default: false,
            },
        },
    });
</script>

// KeyBook/Svelte/src/components/PersonDetails.svelte
﻿<svelte:options tag="person-details-svelte" />
<script lang="ts">
    export let name;
    export let type;
    export let isgone;
    export let hideisgone = false;
    export let disabletype = false;

    let personTypes = {};

    import { getPersonTypes } from '../api/get-types';
    getPersonTypes(r => {
        personTypes = r.data;
        type = String(type) // select value cannot recognise numbers
    }, e => { alert('error: ' + e); /* Add error handling later */ });
</script>
<main>
    <div>
        <div>
            <label for="name">Person Name:</label>
        </div>
        <div>
            <input type="text" name="name" id="name" bind:value="{name}" />
        </div>
        {#if !hideisgone}
            <div>
                <label for="isgone">Person Is Gone:</label>
            </div>
            <div>
                <input type="checkbox" name="isgone" id="name" bind:checked="{isgone}" />
            </div>
        {/if}
        <div>
            <label for="type">Person Type:</label>
        </div>
        <div>
            <select name="type" id="type" bind:value={type} disabled={disabletype}>
                {#each Object.keys(personTypes) as key}
                    <option value={key}>{personTypes[key]}</option>
                {/each}
            </select>
        </div>
        {isgone}
    </div>
</main>
