// Frontend/src/routes/PersonEdit.vue
<template>
    <div v-if="person">
        <person-details v-bind:person="person" v-bind:disableType="true"></person-details>
        <div v-if="person.personDevices && person.personDevices.length > 0">
            <div class="persns-devices">
                <table>
                    <tr>
                        <th>Device Name</th>
                        <th>Device Identifier</th>
                        <th>Status</th>
                        <th>Type</th>
                        <th></th>
                    </tr>
                    <tr v-for="personDevice in person.personDevices" v-bind:key="personDevice.id">
                        <td>{{ personDevice.device.name }}</td>
                        <td>{{ personDevice.device.identifier }}</td>
                        <td>{{ personDevice.device.status }}</td>
                        <td>{{ personDevice.device.type }}</td>
                        <td></td>
                    </tr>
                </table>
            </div>
        </div>
        <div v-else>
            Person has no devices
        </div>
    </div>
    <div v-else>
        Can't find person details.
    </div>
</template>

<script lang="ts">
    import Vue from 'vue';

    export default Vue.extend({
        name: 'person-edit',
        props: ['personId'],
        data() {
            return {
                person: null
            };
        },
        created() {
            this.fetchPersonDetails();
        },
        watch: {
            '$route': 'fetchPersonDetails'
        },
        methods: {
            fetchPersonDetails(): void {
                this.person = null;
                fetch('person/view/id/' + this.personId).then(r => r.json()).then(data => {
                    this.person = data;
                });
            }
        },
    });
</script>

// KeyBook/Svelte/src/components/PersonEdit.svelte
﻿<svelte:options tag="person-edit-svelte" />
<script lang="ts">
	export let personjson;

    let person = JSON.parse(personjson);
    import PersonDetails from './PersonDetails.svelte';
    let saveableDetails = ["name", "type"];
</script>
<main>
    <PersonDetails bind:name={person.name} bind:type={person.type} bind:isgone={person.isGone} disabletype=true />
    {#if person.personDevices && person.personDevices.length > 0}
        <div>
            <label for="name">Devices Held:</label>
        </div>
        <div class="persns-devices">
            <table>
                <tr>
                    <th>Device Name</th>
                    <th>Device Identifier</th>
                    <th>Type</th>
                    <th></th>
                </tr>
                {#each person.personDevices as personDevice}
                    <tr>
                        <td>{personDevice.device.name}</td>
                        <td>{personDevice.device.identifier}</td>
                        <td>{personDevice.device.type}</td>
                        <td>
                            <button on:click={
                                () => window.location.href = "/Device/Edit/" + personDevice.device.id + "?fromPersonDetailsPersonId=" + person.id
                            }>Details</button>
                        </td>
                    </tr>
                {/each}
            </table>
        </div>
    {/if}
    <div>
        <form action="/Person/Save" method="POST">
            <input type="hidden" name="personid" id="personid" value={person.id} />
            {#each saveableDetails as saveableDetail}
                <input type="hidden" name="{saveableDetail}" id="{saveableDetail}" value="{person[saveableDetail]}" />
            {/each}
            <button>Save person</button>
        </form>
    </div>
</main>
